### ISSUE TITLE
Bug in timeseries_anomalies.py

### ISSUE THREAD

**Issue by itinawi** [HDI-Project/MLPrimitives#119]
In `mlprimitives/custom/timeseries_anomalies.py` I got an error when producing anomalies from the NASA telemanom paper. I got the following error log.

```
/home/itinawi/virtualenvs/mlprimitives/lib/python3.6/site-packages/scipy/optimize/optimize.py:570: RuntimeWarning: invalid value encountered in subtract
  numpy.max(numpy.abs(fsim[0] - fsim[1:])) <= fatol):
ERROR:mlblocks.mlpipeline:Exception caught producing MLBlock timeseries_anomalies.find_anomalies#1
Traceback (most recent call last):
  File "/home/itinawi/virtualenvs/mlprimitives/lib/python3.6/site-packages/mlblocks/mlpipeline.py", line 264, in predict
    outputs = block.produce(**produce_args)
  File "/home/itinawi/virtualenvs/mlprimitives/lib/python3.6/site-packages/mlblocks/mlblock.py", line 268, in produce
    return self.primitive(**produce_args)
  File "/home/itinawi/Desktop/coding/meng/IML-private/Orion/analysis/timeseries_anomalies.py", line 167, in find_anomalies
    anomalies.append([index[start], index[stop], score])
IndexError: index 2564 is out of bounds for axis 0 with size 2564
Traceback (most recent call last):
  File "run_pipelines.py", line 71, in <module>
    anoms = pipeline.predict(test)
  File "/home/itinawi/virtualenvs/mlprimitives/lib/python3.6/site-packages/mlblocks/mlpipeline.py", line 264, in predict
    outputs = block.produce(**produce_args)
  File "/home/itinawi/virtualenvs/mlprimitives/lib/python3.6/site-packages/mlblocks/mlblock.py", line 268, in produce
    return self.primitive(**produce_args)
  File "/home/itinawi/Desktop/coding/meng/IML-private/Orion/analysis/timeseries_anomalies.py", line 167, in find_anomalies
    anomalies.append([index[start], index[stop], score])
IndexError: index 2564 is out of bounds for axis 0 with size 2564
```

I can provide additional details of the signal used, but I think the problem is from this line:
https://github.com/HDI-Project/MLPrimitives/blob/master/mlprimitives/custom/timeseries_anomalies.py#L138
The `end` value is larger than the `index` list (off-by-one), so we need to append `len(above)-1`

**Comment by csala** [comment]
Thanks @itinawi I'll look into it!

Can you show instructions to reproduce the error here?

**Comment by csala** [comment]
Confirmed. This happens when there is an anomalous sequence that ends with the timeseries, and the reason is that the intervals that were being returned were open ended '[start, stop)` when they should be close ended: `[start, stop]`.

The solution is to shift all the `ends` array down by one position before building the actual intervals.
